version: '3'

env:
  NAME: raccoon

tasks:
  deps:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - git submodule update --init --recursive
      - conan install . -s build_type=Debug -b missing -pr cpp20 -pr:b cpp20

  init:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --preset=dev

  build:
    dir: '{{.USER_WORKING_DIR}}'
    preconditions:
      - test -f CMakeUserPresets.json
    cmds:
      - cmake --build --preset=dev

  run:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: build
      - cmd: ./scripts/check_redis.sh
        platforms: [linux, openbsd, darwin]
      - cmd: ./scripts/check_proxy.sh
        platforms: [linux, openbsd, darwin]
      - ./build/dev/{{.NAME}}

  run-v:
    cmds:
      - task: build
      - ./build/dev/{{.NAME}} -v

  test:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - task: build
      - ctest --preset=dev

  docs:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev -t docs
      - cmake --build --preset=dev -t docs-serve

  clean:
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmake --build --preset=dev -t clean

  default:
    cmds:
      - task: run-v
